CC=gcc
CFLAGS=-O2 -lbufro -lX11 -lGL -lGLU -lglfw -lm

quickstart: quickstart.c
	$(CC) quickstart.c $(CFLAGS) -o quickstart

alpha: alpha.c
	$(CC) alpha.c $(CFLAGS) -o alpha

polygon: polygon.c
	$(CC) polygon.c $(CFLAGS) -o polygon
